name: ftth
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  intl: ^0.20.2
  geolocator: ^13.0.2
  logger: ^2.5.0
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  get: ^4.7.3
  loading_animation_widget: ^1.3.0
  toastification: ^3.0.3
  shared_preferences: ^2.5.4
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
